include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    eol_at_end_of_file: true
    public_member_api_docs: false
    require_trailing_commas: false

analyzer:
  errors:
    invalid_annotation_target: ignore
    lines_longer_than_80_chars: ignore


  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
