name: shopengo
description: "Your designated shopping buddy"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  kiwi: ^5.0.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true