name: shopengo
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  kiwi: ^5.0.1
  go_router: ^14.8.1
  easy_localization: ^3.0.7+1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  cupertino_icons: ^1.0.8
  build_runner: ^2.4.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true