name: shopengo
description: "Your designated shopping buddy"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.17
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  kiwi: ^5.0.1
  path_provider: ^2.1.5

dependency_overrides:
  analyzer: 7.3.0

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.0
  flutter_gen: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  mockito: ^5.4.6
  very_good_analysis: ^7.0.0

flutter_gen:
  output: lib/generated/

  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      class_name: Assets

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/fonts/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-SemiBold.ttf